### ISSUE TITLE
Syntax Error unter TYPO3 10 mit PHP7.4

### ISSUE THREAD

**Issue by WSBusch** [PKuhlmay/treupo_sys_note_widgets#5]
Wir möchten die Extension in einem 10er TYPO3 mit vielen sys_notes einsetzen.
Unter PHP 7.4 erhalten wir jedoch den Fehler

`(1/1) ParseError
syntax error, unexpected 'private' (T_PRIVATE), expecting variable (T_VARIABLE)
in /var/www/html/typo3conf/ext/treupo_sys_note_widgets/Classes/Widgets/PageOverviewWidget.php line 21`

**Comment by PKuhlmay** [comment]
Danke für das Issue, ich schaue mir das mal an.

**Comment by PKuhlmay** [comment]
Hallo @WSBusch Der Fehler sollte behoben sein. Ich hatte versehentlich PHP Code genutzt, der in PHP 7.4 nicht mehr kompatibel ist, dafür nur in 8+. Nun läuft es auf TYPO3 10-12 und PHP 7.4-8.1
